stages:
  - build



latest:
  stage: build
  image: docker:stable
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_TAG $CONTAINER_TEST_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

  rules:
    - if: $CI_COMMIT_TAG
