stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_TAG $CONTAINER_TEST_IMAGE:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

  rules:
    - if: $CI_COMMIT_TAG

